import { type GuideTopic, note, p, repoDoc, table } from './types'

const topic: GuideTopic = {
  zh: {
    slug: 'commands',
    locale: 'zh-CN',
    navTitle: '命令参考',
    title: 'dsh-TUI Slash Commands 命令参考',
    description: 'dsh-TUI 斜杠命令全集：会话、状态与诊断、模型与显示、账号策略与扩展、技能，以及来自 DSH 注册表的 /plan、/goal 等命令。',
    intro: '在输入框键入 / 打开命令菜单。命令菜单 = 内置命令（50 条）+ DSH 注册表命令（`/plan` `/goal` 等）+ 技能目录（仅补全，`/help` 菜单隐藏）。`/lang` 可切换中英文界面与命令描述。',
    sections: [
      {
        heading: '会话',
        id: 'session',
        aliases: ['section-1'],
        blocks: [
          table(['命令', '参数', '作用'], [
            ['`/new`', '无', '新开会话（无二次确认；旧会话可 `/resume` 恢复）'],
            ['`/resume`', '无', '打开**会话管理界面**（工作区栏 + 会话栏、实时筛选、固定常用、跨工作区）：切换会话只是**停放**，正在跑的回合不中断'],
            ['`/home` / `/agentview` / `/bg`', '无', '同一个会话管理界面（`/home`=工作区视角 · `/agentview`=托管会话状态 · `/bg`=转后台并打开，别名 `/background`）'],
            ['`/tree`', '无', '会话分叉树：悬停预览、点击回退 / 分叉 / 切换分支'],
            ['`/fork`', '无', '把当前会话复制成可恢复的副本（原会话不受影响）'],
            ['`/restart`', '无', '重启进程并恢复本会话（回合运行中会被拒绝，先 `Ctrl+C`）'],
            ['`/rename`', '`<新名称>`', '重命名当前会话（无参时显示当前标题与用法）'],
            ['`/recap`', '无', '最近活动摘要（一行）+ 建议标题；面板内 `a` 键或点击一键应用标题。设置 `dsh-tui.recapOnOpen`（默认开）开启时，打开/恢复会话自动在底部显示一条分隔线 + `回顾：` 摘要行，悬停可查看操作、点击展开，发送新消息后自动消失'],
            ['`/workspace`', '`resume` / `rename <名称>` / `open <路径或URI>`', '管理工作区；`open` 支持绝对路径、file URI、插件 scheme'],
            ['`/clear`', '无', '清空当前会话视图（重置展开/选择状态）'],
            ['`/compact`', '无', '压缩会话历史（无可压缩内容时会提示）'],
            ['`/export`', '无', '导出会话为 Markdown 到工作目录'],
            ['`/btw`', '`<问题>`', '侧问：单轮、无工具、不打断主回合、不写历史'],
            ['`/trace`', '无', '打开轨迹场景（同 `Ctrl+T`）'],
            ['`/rewind`', '无', '回退选择器（同空输入双击 Esc 的时间回溯）'],
            ['`/exit`（别名 `/quit` `/q`）', '无', '退出 dsh-tui'],
          ]),
        ],
      },
      {
        heading: '状态与诊断',
        id: 'status',
        aliases: ['section-2'],
        blocks: [
          table(['命令', '参数', '作用'], [
            ['`/context`', '无', '已加载上下文明细（指令/运行时上下文/技能/工具等）'],
            ['`/status`', '无', '模型+effort、工作/空闲、会话 id、目录+git 分支、token、缓存命中率、上下文百分比、会话标题'],
            ['`/cost`', '无', 'token 用量 + 缓存命中率（DSH 不提供费用计量）'],
            ['`/balance`', '无', 'DeepSeek 官方账户余额（免费只读接口）：摘要行 + hover 明细，点击刷新、`×` 关闭'],
            ['`/config`', '无', '配置来源：`cordis.patch.yml` 路径、启动方式、模型路由'],
            ['`/doctor`', '无', '环境自检'],
            ['`/migrate`', '`[agent] [--dry-run]`', `从其他编程代理（claude-code/codex/omp/zcode/grok-build）导入对话历史，子进程运行不卡界面，详见[会话迁移](${repoDoc('migrate.md')})`],
            ['`/init`', '无', '在工作目录创建 `AGENTS.md`（created / exists / failed 三态提示）'],
            ['`/agents`', '无', '本会话子代理列表'],
            ['`/jobs`', '无', '后台任务面板：状态/运行时长/退出码实时跟踪，`↑/↓` 选择、`k` 停止；面板打开时 `Esc` **只关面板**不打断回合（想中断先关面板再 `Ctrl+C`）'],
            ['`/settings`', '无', '打开插件设置编辑器（命名空间读取/编辑）；全部设置项见[设置项参考](../settings/)'],
            ['`/help`', '无', '快捷键 + 命令帮助菜单（`?` 入口）'],
          ]),
        ],
      },
      {
        heading: '模型与显示',
        id: 'model',
        blocks: [
          table(['命令', '参数', '作用'], [
            ['`/model`', '无', '模型选择器；**切换 = fork 会话续聊**（历史保留、仅换路由），选择持久化到 `~/.dsh-tui/model.json`'],
            ['`/effort`', '`status` / `<id>`', '推理强度：无参滑杆（`←/→` 实时调整）；`status` 当前档位；`<id>` 直接设定。持久化 `~/.dsh-tui/effort.json`；新会话起始档看 /settings 的 `effortDefault`'],
            ['`/thinking`', '无', '扩展思考显示开关（流式时思考逐条展开）'],
            ['`/tokens`', '无', 'token 用量 + 上下文百分比'],
            ['`/activity`', '`frames <名>` / `status`', '工作状态行动画：无参选择器浏览，`frames <名>` 直接设置（含 `random`），默认 `moon8`。持久化 `~/.dsh-tui/working-activity.json`'],
            ['`/preset`', '`<id>` / `status`', 'Agent 预设切换：`standard` / `ptc`（旧 0.1.1 名 `code`）/ `minimal` / `cordis` / **梁神模式 `liangshen`**；**已开始的会话不可切换**。持久化 `~/.dsh-tui/agent-preset.json`'],
            ['`/theme`', '`<名字>` / `status`', '主题：无参选择器；`<名字>` 直接切换；`status` 当前主题（auto 时附 OSC 11 解析结果）。持久化 `~/.dsh-tui/theme.json`'],
            ['`/color`', '无参 / `<名>` / `status` / `reset`', '会话强调色：无参打开调色板（`↑/↓` 选、`Enter` 应用）；`<名>` 直设；`reset` 恢复默认。颜色 `red/orange/yellow/green/blue/purple/pink/cyan`，按会话保存'],
            ['`/lang`', '`en` / `zh` / `status`', '界面语言热切换。优先级：`DSH_TUI_LANG` > profile 配置（旧版 settings.yaml 用户层 > cordis.yml）> 持久化'],
            ['`/vim`', '无', '**vim 编辑模式开关**：输入框切到 vim 键位编辑，会话级、不持久化（键位见[快捷键](../shortcuts/)）'],
          ]),
        ],
      },
      {
        heading: '账号、策略与扩展',
        id: 'account',
        aliases: ['section-3'],
        blocks: [
          table(['命令', '参数', '作用'], [
            ['`/provider`', '无', '交互式管理模型提供方（添加 / 编辑 / 删除；捆绑 dsh-auth 时可 **OAuth 订阅登录** ChatGPT / Claude / Grok，免 API key）'],
            ['`/login`', '无', '凭证状态（来源、存储可写性、base URL）'],
            ['`/logout`', '无', '登出说明（env 来源需删环境变量并重启）'],
            ['`/permission`', '无 / `<preset>` / `status`', '查看/切换权限预设与策略（无参打开选择器）'],
            ['`/add-dir`', '无', '文件策略范围说明（以工作目录为根）'],
            ['`/hooks`', '无', '占位：DSH hooks 未在组合中挂载时给出说明'],
            ['`/mcp`', '无', 'MCP 连接状态（工具按 `mcp__服务器__工具` 分组）；未配置时给出 `cordis.patch.yml` 插入示例'],
            ['`/skills`', '无', '技能目录选择器（名称+来源+简述），Enter 将可直调技能以 `/name ` 填回输入行'],
            ['`/plugins`', '`check <dsh-plugin.json 路径>`', '插件诊断：信任横幅 + host 描述符 + 授权矩阵 + 台账；`check` 校验清单文件并给兼容状态'],
            ['`/update`', '无', '更新 TUI 并自动重启恢复会话（仅 `dsh --profile` 启动可用；回合运行中会拒绝）'],
            ['`/terminal-setup`', '无', '终端配置建议（Windows Terminal ≥110 列、粘贴键位）'],
          ]),
        ],
      },
      {
        heading: '技能与占位命令',
        id: 'skills',
        aliases: ['section-4'],
        blocks: [
          p('dsh-TUI 不预装通用技能；`/skills` 浏览 DSH 发现的技能，可直调技能以 `/name` 加入命令菜单（详见[会话工作流](../sessions/)）。'),
          p('`/connect`：占位——DSH 暂无远程连接机制。'),
        ],
      },
      {
        heading: '注册表命令',
        id: 'registry',
        blocks: [
          p('以下命令来自 DSH 生态，随组合动态并入 `/` 菜单。'),
          table(['命令', '作用'], [
            ['`/plan`', '`[off|message]` 计划模式；`/plan off` 退出'],
            ['`/goal`', '设置/查看会话目标'],
            ['`/feedback`', '提交使用反馈'],
            ['`/permission`', '查看/切换 DSH `permissionPresets` registry 的预设（第三方预设按 registry 顺序显示）'],
          ]),
          note('这些命令由 DSH 命令注册表实现，dsh-TUI 只做菜单并入、补全与分发。'),
        ],
      },
    ],
  },
  en: {
    slug: 'commands',
    locale: 'en',
    navTitle: 'Commands',
    title: 'dsh-TUI Slash Command Reference',
    description: 'Every dsh-TUI slash command: session, status and diagnostics, model and display, accounts and extensions, skills, plus DSH registry commands such as /plan and /goal.',
    intro: 'Type / in the prompt to open the command menu. The menu = built-in commands (50) + DSH registry commands (`/plan` `/goal` etc.) + the skill catalog (completion only, hidden from the `/help` menu). `/lang` switches the UI and command descriptions between English and Chinese.',
    sections: [
      {
        heading: 'Session',
        id: 'session',
        aliases: ['section-1'],
        blocks: [
          table(['Command', 'Args', 'Effect'], [
            ['`/new`', 'none', 'start a new session (no confirmation; the old session stays under `/resume`)'],
            ['`/resume`', 'none', 'open the **session manager** (workspace + session columns, live filter, pins, cross-workspace): switching just parks the session, the running turn keeps going'],
            ['`/home` / `/agentview` / `/bg`', 'none', 'the same session manager (`/home` = workspace view · `/agentview` = hosted session state · `/bg` = send to background and open, alias `/background`)'],
            ['`/tree`', 'none', 'session fork tree: hover to preview, click to rewind / fork / switch branch'],
            ['`/fork`', 'none', 'copy the current session into a resumable clone (original unaffected)'],
            ['`/restart`', 'none', 'restart the process and resume this session (rejected mid-turn, `Ctrl+C` first)'],
            ['`/rename`', '`<new-name>`', 'rename the current session (no arg shows the current title and usage)'],
            ['`/recap`', 'none', 'recent-activity summary (one line) + suggested title; press `a` or click to apply the title. With `dsh-tui.recapOnOpen` (default on), opening/resuming a session auto-shows a divider + recap summary line at the bottom; hover to view actions, click to expand, gone after the next message'],
            ['`/workspace`', '`resume` / `rename <name>` / `open <path-or-URI>`', 'manage workspaces; `open` accepts an absolute path, file URI, or plugin scheme'],
            ['`/clear`', 'none', 'clear the current session view (reset expand/selection state)'],
            ['`/compact`', 'none', 'compact session history (prompts when nothing to compact)'],
            ['`/export`', 'none', 'export the session as Markdown to the working directory'],
            ['`/btw`', '`<question>`', "side question: single turn, no tools, doesn't interrupt the main turn, not written to history"],
            ['`/trace`', 'none', 'open the trace scene (same as `Ctrl+T`)'],
            ['`/rewind`', 'none', 'rewind selector (same as double-press Esc on empty input)'],
            ['`/exit` (alias `/quit` `/q`)', 'none', 'exit dsh-tui'],
          ]),
        ],
      },
      {
        heading: 'Status and diagnostics',
        id: 'status',
        aliases: ['section-2'],
        blocks: [
          table(['Command', 'Args', 'Effect'], [
            ['`/context`', 'none', 'loaded-context detail (instructions/runtime context/skills/tools etc.)'],
            ['`/status`', 'none', 'model+effort, working/idle, session id, dir+git branch, token, cache hit rate, context percentage, session title'],
            ['`/cost`', 'none', 'token usage + cache hit rate (DSH provides no cost metering)'],
            ['`/balance`', 'none', 'DeepSeek official account balance (free read-only API): summary line + hover detail, click refresh, `×` close'],
            ['`/config`', 'none', 'config sources: `cordis.patch.yml` path, launch method, model routing'],
            ['`/doctor`', 'none', 'environment check'],
            ['`/migrate`', '`[agent] [--dry-run]`', `import conversation history from other coding agents (claude-code/codex/omp/zcode/grok-build); runs in a child process — see [Session migration](${repoDoc('migrate.en.md')})`],
            ['`/init`', 'none', 'create `AGENTS.md` in the working directory (created / exists / failed)'],
            ['`/agents`', 'none', 'subagent list for this session'],
            ['`/jobs`', 'none', "background-task panel: status/runtime/exit-code tracking, `↑/↓` select, `k` stop; while open, `Esc` **closes only the panel** and won't interrupt the turn (close the panel first, then `Ctrl+C`)"],
            ['`/settings`', 'none', 'open the plugin settings editor (namespace read/edit); every key is listed in the [settings reference](../settings/)'],
            ['`/help`', 'none', 'shortcut + command help menu (`?` entry)'],
          ]),
        ],
      },
      {
        heading: 'Model and display',
        id: 'model',
        blocks: [
          table(['Command', 'Args', 'Effect'], [
            ['`/model`', 'none', 'model selector; **switching = fork the session** (history kept, only routing changes), choice persisted to `~/.dsh-tui/model.json`'],
            ['`/effort`', '`status` / `<id>`', 'reasoning effort: no-arg slider (`←/→` adjust); `status` current level; `<id>` set directly. Persisted to `~/.dsh-tui/effort.json`; new-session start level follows the `effortDefault` setting'],
            ['`/thinking`', 'none', 'extended-thinking display toggle (thinking expands item by item while streaming)'],
            ['`/tokens`', 'none', 'token usage + context percentage'],
            ['`/activity`', '`frames <name>` / `status`', 'working-status animation: no-arg selector, `frames <name>` sets directly (includes `random`), default `moon8`. Persisted to `~/.dsh-tui/working-activity.json`'],
            ['`/preset`', '`<id>` / `status`', 'agent preset: `standard` / `ptc` (old 0.1.1 name `code`) / `minimal` / `cordis` / **Liangshen mode `liangshen`**; **cannot switch an already-started session**. Persisted to `~/.dsh-tui/agent-preset.json`'],
            ['`/theme`', '`<name>` / `status`', 'theme: no-arg selector; `<name>` switch directly; `status` current theme (auto appends the OSC 11 result). Persisted to `~/.dsh-tui/theme.json`'],
            ['`/color`', 'no-arg / `<name>` / `status` / `reset`', 'session accent color: no-arg opens the palette (`↑/↓` pick, `Enter` apply); `<name>` set directly; `reset` back to default. Colors `red/orange/yellow/green/blue/purple/pink/cyan`, saved per session'],
            ['`/lang`', '`en` / `zh` / `status`', 'hot-switch UI language. Priority: `DSH_TUI_LANG` > profile config (legacy: settings.yaml user layer > cordis.yml) > persisted'],
            ['`/vim`', 'none', '**vim editing mode toggle**: input switches to vim keys, per-session, not persisted (keys on the [shortcuts](../shortcuts/) page)'],
          ]),
        ],
      },
      {
        heading: 'Account, policy, and extensions',
        id: 'account',
        aliases: ['section-3'],
        blocks: [
          table(['Command', 'Args', 'Effect'], [
            ['`/provider`', 'none', 'interactive model-provider wizard (add / edit / delete; with dsh-auth bound, **OAuth subscription login** for ChatGPT / Claude / Grok, no API key)'],
            ['`/login`', 'none', 'credential status (source, store writability, base URL)'],
            ['`/logout`', 'none', 'logout notes (env source: delete the variable and restart)'],
            ['`/permission`', 'none / `<preset>` / `status`', 'view/switch permission preset and policy (no arg opens the selector)'],
            ['`/add-dir`', 'none', 'file-policy scope notes (rooted at the working directory)'],
            ['`/hooks`', 'none', "placeholder: notes when DSH hooks aren't mounted in the composition"],
            ['`/mcp`', 'none', 'MCP connection state (tools grouped as `mcp__server__tool`); shows a `cordis.patch.yml` snippet when unconfigured'],
            ['`/skills`', 'none', 'skill-catalog selector (name+source+blurb); Enter fills a direct-call skill as `/name `'],
            ['`/plugins`', '`check <path-to-dsh-plugin.json>`', 'plugin diagnostics: trust banner + host descriptor + authorization matrix + ledger; `check` validates a manifest and reports compatibility'],
            ['`/update`', 'none', 'update the TUI and auto-restart to resume the session (only via `dsh --profile`; rejected mid-turn)'],
            ['`/terminal-setup`', 'none', 'terminal setup advice (Windows Terminal ≥110 columns, paste keys)'],
          ]),
        ],
      },
      {
        heading: 'Skills and placeholder commands',
        id: 'skills',
        aliases: ['section-4'],
        blocks: [
          p('dsh-TUI ships no generic skills; `/skills` browses skills DSH discovers, and a direct-call skill joins the command menu as `/name` (see [session workflow](../sessions/)).'),
          p('`/connect`: placeholder — DSH has no remote-connection mechanism yet.'),
        ],
      },
      {
        heading: 'Registry commands',
        id: 'registry',
        blocks: [
          p('These come from the DSH ecosystem and are merged into the `/` menu with the composition.'),
          table(['Command', 'Effect'], [
            ['`/plan`', '`[off|message]` plan mode; `/plan off` exits'],
            ['`/goal`', 'set/view the session goal'],
            ['`/feedback`', 'submit usage feedback'],
            ['`/permission`', 'view/switch presets from the DSH `permissionPresets` registry (third-party presets in registry order)'],
          ]),
          note('These commands come from the DSH command registry; dsh-TUI only merges them into the menu, completes, and dispatches.'),
        ],
      },
    ],
  },
}

export default topic
