import { type GuideTopic, h3, note, p, repoDoc, table, ul } from './types'

const topic: GuideTopic = {
  zh: {
    slug: 'shortcuts',
    locale: 'zh-CN',
    navTitle: '快捷键',
    title: 'dsh-TUI 快捷键与终端操作',
    description: 'dsh-TUI 键盘快捷键速查：发送与投递、中断退出、搜索、输入编辑、鼠标选择，以及问卷、审批、会话管理等各场景键位。',
    intro: '快捷键围绕终端肌肉记忆设计。表内 `Ctrl` 在 macOS 上大多可换 `⌘`（`⌘V` `⌘O` `⌘R` `⌘T` `⌘L` `⌘Enter`），`Ctrl+C`/`Ctrl+D` 不变；`⌘` 需要终端支持扩展键盘协议，Terminal.app 请用 Ctrl。',
    sections: [
      {
        heading: '发送与投递',
        id: 'send',
        blocks: [
          p('模型工作时，同一段输入有三种投递语义：steer、follow-up 与 interrupt。'),
          table(['键', '功能'], [
            ['`Enter`', '空闲=发送；**模型工作时=steer**（注入下一步边界，不中断）；菜单打开=确认选中项'],
            ['`Tab`', '补全 `/` 命令或 `@` 文件；**模型工作时=follow-up**（排入当前回合之后）'],
            ['`Ctrl+Enter`（⌘Enter）', '打断当前回合并立即发送输入'],
            ['`Shift+Enter` / `Ctrl+J`', '换行（`Option+Enter` 是 mac Terminal.app 的兜底）'],
            ['`Alt+Up`', '把最后一条未处理消息取回输入框编辑（不中断回合）'],
            ['`Esc`（工作 + 有 pending）', '中断回合并立即重投 pending 消息'],
            ['工作中的 `/btw …`', 'Enter 直接执行（侧问永不打断主回合）'],
          ]),
        ],
      },
      {
        heading: '中断、退出与系统',
        blocks: [
          table(['键', '功能'], [
            ['`Ctrl+C`', '工作中=中断；中断未收敛时再按=强制退出；空闲有输入=清空输入；空闲空输入=双击退出（3 秒窗口）'],
            ['`Ctrl+D`', '工作中=中断（中断未收敛时再按=强制退出）；空闲时双击退出'],
            ['`Ctrl+L`（⌘L）', '清屏并强制重绘'],
            ['`Ctrl+O`（⌘O）', '展开/收起详情（思考全文、工具参数与输出）'],
            ['`Ctrl+E`', '输入框=光标到行尾；转录中=展开/折叠隐藏的旧消息'],
            ['`Ctrl+P`', '切换启动时 loaded-context 面板（面板在屏时有效）'],
            ['`?`', '输入框为空时打开快捷键/命令帮助菜单'],
          ]),
        ],
      },
      {
        heading: '搜索',
        blocks: [
          table(['键', '功能'], [
            ['`Ctrl+R`（⌘R）', '历史消息搜索；重复按或 `↓` 到下一匹配；`Enter` 回填输入框'],
            ['`/`（转录态）', '会话全文搜索；`n` / `N` 跳转（仅 Ctrl+O 展开态）'],
          ]),
        ],
      },
      {
        heading: '输入编辑',
        blocks: [
          table(['键', '功能'], [
            ['`←` / `→`', '按字符移动光标（有选区时坍缩到选区对应边缘）'],
            ['`Ctrl+←` / `Ctrl+→`（⌘←/→）', '按词跳转'],
            ['`Home` / `End`，`Ctrl+E`', '逻辑行首 / 行尾（`Ctrl+A` 已改用于子代理面板，见下方各场景键位）'],
            ['`Ctrl+U` / `Ctrl+K`', '删除光标前（至行首）/ 光标后（至行尾）'],
            ['`Ctrl+W`', '删除前一个单词'],
            ['`Backspace` / `Delete`', '删前一 / 后一字符；**有选区时删除整个选区**'],
            ['`↑` / `↓`', '多行时行间移动；单行时浏览输入历史（最近 200 条，跨重启保留）'],
            ['`Ctrl+V`（⌘V）/ `Alt+V`', '粘贴：文本 / 文件路径（图片自动 `@` 引用）/ 剪贴板位图（`[Image #N]` 附件）；终端拦截 `Ctrl+V` 时用 `Alt+V`'],
            ['`Ctrl+G`', '用 `$VISUAL`/`$EDITOR` 外部编辑器编辑输入（`:cq` 保留原稿；未设置变量时提示配置）'],
            ['`Ctrl+Shift+E`（⌘⇧E）', '展开**全屏草稿编辑器**（也可点输入行尾 `⛶`）：带行号、高亮当前行，`Enter` 换行、`Ctrl+Enter` 发送、`Esc` 收起（草稿还在）；可在 `/settings` 关闭'],
            ['超长草稿自动折叠', '粘贴 **≥6 行或 ≥600 字**的块折成 `▸ N 行・M 字` 小条：点小条或 `▾` 切换折叠；`Enter` 提交的始终是全文'],
            ['`/vim`', '**vim 编辑模式开关**（会话级、不持久化）：开启后输入框显示 `INSERT` 徽标，`Esc` 切 `NORMAL`，`i/I/a/A/o/O` 回 INSERT'],
            ['打字', '**有选区时替换整个选区**（和标准编辑器一致），光标落在插入文本之后'],
            ['右键 / `Ctrl+Shift+V`', '终端原生粘贴（含换行原样插入）'],
            ['`Esc`（输入框）', '一层层关：帮助 → **图片预览** → 命令菜单 → 文件菜单（只关当前 `@` token）→ **有选区就先清选区（文字不动）** → 中断重投 → 有输入清空 → 双击=时间回溯'],
            ['双击 `Esc`（空输入）', '**时间回溯 rewind**（3 秒窗口内按两次）'],
          ]),
          p('**vim NORMAL 键位**：移动 `h/l` `j/k` `0/^/$` `w/b`；删除 `x/X` `dd`/`d$`/`d0`/`d^`/`dw`；`u` 撤销、`Enter` 发送。未识别键忽略，`Esc` 无操作，清空用 `Ctrl+C`/`dd`。'),
        ],
      },
      {
        heading: '导航与模式',
        blocks: [
          table(['键', '功能'], [
            ['`Shift+Tab`', '循环会话模式（默认 → plan 计划 → full 完全访问）；挂载了第三方权限预设时，它们按 registry 顺序排在循环末尾'],
            ['`Shift+↑`', '消息选择模式（`↑/↓` 移动，`Enter` 展开单条，`Esc` 退出）'],
            ['`Ctrl+T`（⌘T）', '打开轨迹场景（同 `/trace`）'],
            ['`Alt+S`', '一键 star（同 `/star`；开屏那句求 star 标语整行也可点）。键位可在 `/settings` 改；成功后会演一小段「鲸鱼娘接住星星」的庆祝'],
          ]),
          note('想随时看 star 庆祝：`DSH_TUI_STAR_MODAL=1 dsh-tui`；想看开屏求 star 标语：`DSH_TUI_STAR_LINE=1 dsh-tui`。两者都是预览用环境变量，不动账本。'),
        ],
      },
      {
        heading: '鼠标',
        blocks: [
          p('以下操作用于 fullscreen 全屏模式：拖拽、双击、三击即选即复制。'),
          table(['操作', '功能'], [
            ['左键拖拽', '选文本，**松开即复制**（OSC 52 + 系统剪贴板工具兜底），自动取消选区'],
            ['双击 / 三击', '选词 / 选行，即选即复制'],
            ['滚轮', '滚动消息列表（±3 行/格）；**有文本选区时随内容平移选区**'],
            ['输入框内', '拖拽 / Shift+click / 双击建立选区；`Backspace`/`Delete` 删选区、打字替换、`←/→` 坍缩、`Esc` 仅清选区、`Ctrl+C` 复制选区'],
            ['`Esc`', '取消选区（不复制）'],
            ['单击', '消息行=展开/收起 · 超链接=打开浏览器 · 「加载更早消息」/StickyHeader/「↓ N new」=加载/跳转'],
            ['悬停截断内容', '停留约 600ms 浮层显示完整内容；拖选文本期间浮层不出现'],
            ['键盘扩展选区', '有选区时 `Shift+←/→/↑/↓/Home/End` 扩展/收缩（跨行环绕）'],
          ]),
        ],
      },
      {
        heading: '各场景键位',
        id: 'per-scene',
        blocks: [
          h3('问卷（模型 ask_user_question）'),
          ul(
            '`↑/↓` 选、`Space` 多选、`Tab` 切自定义回答、`Enter` 提交；`Ctrl+V` 粘贴、`Ctrl+K` 折叠。',
            '`Esc` 第 2 题起返回、第 1 题取消整批；`Ctrl+C` 任意题取消。',
          ),
          h3('计划评审（plan review）'),
          ul('`↑/↓` 移动、`1`/`2` 快选；直接打字 = 填反馈（`Ctrl+V` 粘贴、`Enter` 提交）；`Esc` 打断；**批准必须不带反馈**。'),
          h3('工具审批（approval）'),
          ul('`↑/↓` 移动、`1` 允许（仅本次）、`2` 拒绝、`Enter` 提交；`Esc`/`Ctrl+C` 拒绝。'),
          h3('会话管理界面'),
          p('`/resume`、`/home`、`/agentview`、`/bg`、输入框行首 `⌸` 打开的是同一个界面。'),
          ul(
            '布局：左栏工作区、右栏会话；≥84 列两栏并排，更窄收起工作区栏。',
            '换栏 `←/→`；移动 `↑/↓`/`PgUp`/`PgDn`；**直接打字 = 实时筛选**（按标题/目录/分支/模型）。',
            '进入 `Enter`（第 0 行 = 在该工作区新建会话）；新建 `Ctrl+Enter`/`Ctrl+N`；停止后台会话 `Ctrl+X`。',
            '`Ctrl+L` 重读 · `Shift+Tab` 打开操作菜单 · `Esc` 关提示→清空筛选→离开。',
            '鼠标：点击会话行=进入、点 `★`/`☆` 切固定、右键工作区行出菜单。',
            '输入框空着按 `←`（或 `/bg`）= 转后台并打开本界面，会话继续跑。',
          ),
          p('切换会话只是**停放**——正在跑的回合继续跑；被其他终端占用的会话标红写 `占用 pid <pid>`、点不动，对方退出后恢复。固定项存到 `~/.dsh-tui/session-pins.json`。工作区菜单四项：编辑 / 在此新建 / 重命名 / 从列表移除（**只删登记**，目录与会话日志都保留）。'),
          h3('大图预览'),
          p('点输入框里的 `[Image #N]` 或转录缩略图打开。'),
          ul(
            '`←/→` 上/下一张；底部按钮缩放：`适应`/`100%`/`200%`/`400%`/`800%`；拖动、滚轮平移。',
            '`Esc`/`Ctrl+C`/`Enter` 或点卡片外关闭；底部「打开原图」用系统看图程序打开。',
          ),
          h3('IDE 选区'),
          p('需要 VS Code companion 扩展 `dsh-tui-vscode` ≥ 0.7.0。'),
          ul(
            '编辑器选中代码 → 输入框下方**实时**出现 `⧉ N lines selected` 徽标，提交时选中行**自动附加**进上下文。',
            '转录里有「⧉ Selected N lines from <相对路径>」指示行（附加编辑器里的文本，未保存也带上）。',
            `没装/没连 IDE 时自动跳过、不影响其他功能（详见 [VS Code 扩展文档](${repoDoc('vscode.md')})）。`,
          ),
          h3('历史搜索（Ctrl+R）'),
          p('`↑/↓` 选择 · 重复 `Ctrl+R` 或 `↓` 下一项 · `Enter` 回填 · `Esc`/`Ctrl+C`/`Ctrl+D` 取消'),
          h3('轨迹场景（Ctrl+T / /trace）'),
          ul(
            '`↑/↓`/`PgUp`/`PgDn` 移动 · `←/→`（或 `h`）切换时间线/热点 · `g`/`G` 顶/底 · `q`/`Esc` 退出',
            '`[`/`]` 跳失败点 · `{`/`}` 跳轮次 · `m` 循环投影 · `Enter` 展开详情（`j`/`k` 翻页）· 热点 `t` 排序',
            '`/` 查询行（前缀 `tool:` `kind:` `turn:` `err:` `run:` `>10s` `tok>1k`）',
          ),
          h3('/settings 设置面板'),
          p('`↑/↓` 移动 · `Enter` 展开/切换/编辑 · `←/→` 在**有选项的字段**上循环切换（布尔项仍只响应 `Enter`）· 改动自动保存，`Esc` 退出。全部设置项见[设置项参考](../settings/)。'),
          h3('/btw 侧问面板'),
          p('`↑/↓` 滚动 · `Space`/`Enter`/`Esc` 关闭 · `c` 复制答案 · 等待中 `Esc` 取消'),
          h3('/effort 滑杆'),
          p('`←/→` 实时调整（Esc 不还原）· `Enter`/`Esc` 完成'),
          h3('@ 文件补全'),
          p('`@` 在消息任意位置触发 · `↑/↓` 移动 · `Tab`/`Enter` 接受 · 目录可继续深入 · `Esc` 只关当前 token 菜单'),
          ul(
            '**两种查询**：路径形输入（`@src/` `@./` `@~/` `@D:\\`）只列该目录；普通片段**模糊匹配**（`@ink` 命中 `src/ink/Box.js`）。',
            '图片路径自动变 `[Image #N]` 附件。',
          ),
          h3('子代理面板（Ctrl+A）'),
          p('`↑/↓` 浏览 · `Enter` 查看详情 · `Esc` 关闭；详情页 `←/→` 翻页，运行中 `X` 中断；子代理以卡片行实时展示。面板镜像本会话派出的全部子代理——`subagent`/`send_message` 运行、可续子代理的重派（每轮新任务重置该行）、workflow/ralph 成员——并在恢复会话时从日志重新折叠持久发现事实，重启不再清空面板。无实时计时的历史行以 `⚪` 状态展示，不伪造时长。'),
          h3('双击 Esc 时间回溯（rewind）'),
          p('列表 `↑/↓` + `Enter` 进入确认 · 确认页 `Enter` 回退 / `Esc` 返回 · 插件决策等待中只响应 `Esc`'),
        ],
      },
      {
        heading: '终端兼容性',
        blocks: [
          p('iTerm2、kitty、WezTerm、Ghostty 和 tmux 等终端可提供更完整的扩展键盘支持。macOS Terminal.app 会消费部分 Command 快捷键，此时继续使用 Ctrl 组合键。更多终端要求见[界面与状态栏](../interface/#terminal)。'),
        ],
      },
    ],
  },
  en: {
    slug: 'shortcuts',
    locale: 'en',
    navTitle: 'Shortcuts',
    title: 'dsh-TUI Keyboard Shortcuts',
    description: 'dsh-TUI keymap: send and deliver, interrupt and exit, search, input editing, mouse selection, and per-scene keys for approvals, questionnaires, and sessions.',
    intro: 'The keybindings follow common terminal habits. On macOS, `Ctrl` in these tables can usually be swapped for `⌘` (`⌘V` `⌘O` `⌘R` `⌘T` `⌘L` `⌘Enter`); `Ctrl+C`/`Ctrl+D` stay `Ctrl`. `⌘` needs a terminal with the extended keyboard protocol — in Terminal.app, use Ctrl.',
    sections: [
      {
        heading: 'Send and deliver',
        id: 'send',
        blocks: [
          p('While the model is working, the same input can be delivered three ways: steer, follow-up, or interrupt.'),
          table(['Key', 'Action'], [
            ['`Enter`', 'idle = send; **model working = steer** (inject a next-step boundary, no interrupt); menu open = confirm selection'],
            ['`Tab`', 'complete `/` command or `@` file; **model working = follow-up** (queue after the current turn)'],
            ['`Ctrl+Enter` (⌘Enter)', 'interrupt the current turn and send the input now'],
            ['`Shift+Enter` / `Ctrl+J`', 'newline (`Option+Enter` is the mac Terminal.app fallback)'],
            ['`Alt+Up`', 'bring the last unhandled message back to the input for editing (no interrupt)'],
            ['`Esc` (working + pending)', 'interrupt the turn and re-send the pending message now'],
            ['`/btw …` while working', 'Enter runs it directly (a side question never interrupts the main turn)'],
          ]),
        ],
      },
      {
        heading: 'Interrupt, exit, and system',
        blocks: [
          table(['Key', 'Action'], [
            ['`Ctrl+C`', "working = interrupt; if the interrupt won't settle, press again = force quit; idle with input = clear input; idle empty input = double-press exit (3 s window)"],
            ['`Ctrl+D`', "working = interrupt (press again if it won't settle = force quit); idle = double-press exit"],
            ['`Ctrl+L` (⌘L)', 'clear screen and force redraw'],
            ['`Ctrl+O` (⌘O)', 'expand/collapse details (full thinking, tool args and output)'],
            ['`Ctrl+E`', 'in input = cursor to line end; in transcript = expand/collapse hidden old messages'],
            ['`Ctrl+P`', 'toggle the loaded-context panel at startup (works when the panel is on screen)'],
            ['`?`', 'empty input = open shortcut/command help menu'],
          ]),
        ],
      },
      {
        heading: 'Search',
        blocks: [
          table(['Key', 'Action'], [
            ['`Ctrl+R` (⌘R)', 'history search; press again or `↓` for next match; `Enter` fills the input'],
            ['`/` (transcript)', 'full-transcript search; `n` / `N` jump (only in Ctrl+O expanded state)'],
          ]),
        ],
      },
      {
        heading: 'Input editing',
        blocks: [
          table(['Key', 'Action'], [
            ['`←` / `→`', 'move the cursor by character (with a selection, collapse to that edge)'],
            ['`Ctrl+←` / `Ctrl+→` (⌘←/→)', 'jump by word'],
            ['`Home` / `End`, `Ctrl+E`', 'logical line start / end (`Ctrl+A` now opens the subagent panel, see per-scene keys below)'],
            ['`Ctrl+U` / `Ctrl+K`', 'delete before the cursor (to line start) / after the cursor (to line end)'],
            ['`Ctrl+W`', 'delete the previous word'],
            ['`Backspace` / `Delete`', 'delete previous / next character; **with a selection, delete the whole selection**'],
            ['`↑` / `↓`', 'move between lines when multi-line; browse input history when single-line (last 200 entries, kept across restarts)'],
            ['`Ctrl+V` (⌘V) / `Alt+V`', 'paste: text / file path (images auto `@`-referenced) / clipboard bitmap (`[Image #N]` attachment); use `Alt+V` when the terminal swallows `Ctrl+V`'],
            ['`Ctrl+G`', 'edit the input in the `$VISUAL`/`$EDITOR` external editor (`:cq` keeps the draft; prompts you to configure when unset)'],
            ['`Ctrl+Shift+E` (⌘⇧E)', 'open the **full-screen draft editor** (or click `⛶` at the end of the input line): line numbers, current line highlighted, `Enter` newline, `Ctrl+Enter` send, `Esc` collapse (draft kept); can be turned off in `/settings`'],
            ['long draft auto-fold', 'pasting a block **≥6 lines or ≥600 chars** folds into a compact chip showing line and character counts: click the chip or `▾` to toggle; `Enter` always submits the full text'],
            ['`/vim`', '**vim editing mode toggle** (per-session, not persisted): shows an `INSERT` badge, `Esc` to `NORMAL`, `i/I/a/A/o/O` back to INSERT'],
            ['typing', '**replaces the whole selection when one exists** (like a standard editor), cursor lands after the inserted text'],
            ['right-click / `Ctrl+Shift+V`', 'terminal-native paste (newlines inserted as-is)'],
            ['`Esc` (input)', 'closes layer by layer: help → **image preview** → command menu → file menu (only the current `@` token) → **clear selection if any (text stays)** → re-send interrupt → clear input → double-press = time-travel'],
            ['double-press `Esc` (empty input)', '**time-travel rewind** (press twice within 3 s)'],
          ]),
          p('**vim NORMAL keys**: move `h/l` `j/k` `0/^/$` `w/b`; delete `x/X` `dd`/`d$`/`d0`/`d^`/`dw`; `u` undo, `Enter` send. Unrecognized keys are ignored, `Esc` does nothing, clear with `Ctrl+C`/`dd`.'),
        ],
      },
      {
        heading: 'Navigation and modes',
        blocks: [
          table(['Key', 'Action'], [
            ['`Shift+Tab`', 'cycle session mode (default → plan → full access); mounted third-party permission presets follow in registry order at the end of the cycle'],
            ['`Shift+↑`', 'message selection mode (`↑/↓` move, `Enter` expand one, `Esc` exit)'],
            ['`Ctrl+T` (⌘T)', 'open the trace scene (same as `/trace`)'],
            ['`Alt+S`', 'one-key star (same as `/star`; the splash\'s star line is clickable too). Remappable in `/settings`; a short "the whale girl catches the star" celebration plays on success'],
          ]),
          note('Replay the star celebration any time with `DSH_TUI_STAR_MODAL=1 dsh-tui`; preview the splash star line with `DSH_TUI_STAR_LINE=1 dsh-tui`. Both are preview env vars and leave the ledger untouched.'),
        ],
      },
      {
        heading: 'Mouse',
        blocks: [
          p('These apply in fullscreen mode: drag, double-click, and triple-click select and copy.'),
          table(['Action', 'Effect'], [
            ['left-drag', 'select text, **copy on release** (OSC 52 + system clipboard tools as fallback), auto-clear the selection'],
            ['double-click / triple-click', 'select word / line, copy immediately'],
            ['wheel', 'scroll the message list (±3 rows/notch); **with a text selection, pan the selection with the content**'],
            ['in the input box', 'drag / Shift+click / double-click build a selection; `Backspace`/`Delete` delete it, typing replaces, `←/→` collapse, `Esc` clears only the selection, `Ctrl+C` copies it'],
            ['`Esc`', 'clear the selection (no copy)'],
            ['single-click', 'message row = expand/collapse · hyperlink = open browser · load-earlier row / sticky header / "↓ N new" = load/jump'],
            ['hover truncated content', 'hover ~600 ms to show full content in a popover; no popover while dragging a selection'],
            ['keyboard selection extend', 'with a selection, `Shift+←/→/↑/↓/Home/End` extends/shrinks (wraps across lines)'],
          ]),
        ],
      },
      {
        heading: 'Per-scene keys',
        id: 'per-scene',
        blocks: [
          h3('Questionnaire (model ask_user_question)'),
          ul(
            '`↑/↓` select, `Space` multi-select, `Tab` jump to custom answer, `Enter` submit; `Ctrl+V` paste, `Ctrl+K` fold.',
            '`Esc` goes back from question 2 onward and cancels the whole batch on question 1; `Ctrl+C` cancels on any question.',
          ),
          h3('Plan review'),
          ul('`↑/↓` move, `1`/`2` quick pick; typing = fill feedback (`Ctrl+V` paste, `Enter` submit); `Esc` interrupt; **approve must have no feedback**.'),
          h3('Tool approval'),
          ul('`↑/↓` move, `1` allow (this time only), `2` deny, `Enter` submit; `Esc`/`Ctrl+C` deny.'),
          h3('Session manager'),
          p('`/resume`, `/home`, `/agentview`, `/bg`, and `⌸` at the input line start all open the same screen.'),
          ul(
            'Layout: left workspace column, right session column; ≥84 columns side-by-side, narrower hides the workspace column.',
            'Switch column `←/→`; move `↑/↓`/`PgUp`/`PgDn`; **typing = live filter** (by title/dir/branch/model).',
            'Enter `Enter` (row 0 = new session in that workspace); new `Ctrl+Enter`/`Ctrl+N`; stop background session `Ctrl+X`.',
            '`Ctrl+L` reload · `Shift+Tab` open action menu · `Esc` close hint → clear filter → leave.',
            'Mouse: click a session row = enter, click `★`/`☆` = toggle pin only, right-click a workspace row = action menu.',
            'Empty input + `←` (or `/bg`) = send to background and open this screen; the session keeps running.',
          ),
          p('Switching sessions just parks the current one — the running turn keeps going. A session taken by another terminal shows red with its owner pid and can\'t be entered; it recovers after that terminal exits. Pins live in `~/.dsh-tui/session-pins.json`. The workspace menu has four items: edit / new here / rename / remove from list (**removes the entry only**; the directory and session log stay).'),
          h3('Image preview'),
          p('Open it by clicking `[Image #N]` in the input or a thumbnail in the transcript.'),
          ul(
            '`←/→` previous / next; bottom-button zoom (fit / 100% / 200% / 400% / 800%); drag or wheel to pan.',
            '`Esc`/`Ctrl+C`/`Enter` or click outside to close. The bottom "open original" button opens the file in the system viewer.',
          ),
          h3('IDE selection'),
          p('Needs the VS Code companion extension `dsh-tui-vscode` ≥ 0.7.0.'),
          ul(
            'Select code in the editor → a `⧉ N lines selected` badge appears **live** under the input, and the selected lines are **auto-attached** to context on submit.',
            'The transcript shows a "⧉ Selected N lines from <relative path>" indicator line (text from the editor, unsaved changes included).',
            `No IDE installed or connected → skipped automatically, nothing else affected (see the [VS Code extension docs](${repoDoc('vscode.en.md')})).`,
          ),
          h3('History search (Ctrl+R)'),
          p('`↑/↓` select · press `Ctrl+R` again or `↓` for next · `Enter` fill · `Esc`/`Ctrl+C`/`Ctrl+D` cancel'),
          h3('Trace scene (Ctrl+T / /trace)'),
          ul(
            '`↑/↓`/`PgUp`/`PgDn` move · `←/→` (or `h`) switch timeline/hotspot · `g`/`G` top/bottom · `q`/`Esc` exit',
            '`[`/`]` jump failure · `{`/`}` jump turn · `m` cycle projection · `Enter` expand details (`j`/`k` page) · hotspot `t` sort',
            '`/` query line (prefixes `tool:` `kind:` `turn:` `err:` `run:` `>10s` `tok>1k`)',
          ),
          h3('/settings panel'),
          p('`↑/↓` move · `Enter` expand/toggle/edit · `←/→` cycle a field that has options (booleans still only respond to `Enter`) · changes save automatically, `Esc` exits. Every setting is listed in the [settings reference](../settings/).'),
          h3('/btw panel'),
          p('`↑/↓` scroll · `Space`/`Enter`/`Esc` close · `c` copy answer · `Esc` cancels while waiting'),
          h3('/effort slider'),
          p('`←/→` adjust live (Esc does not revert) · `Enter`/`Esc` done'),
          h3('@ file completion'),
          p('`@` triggers anywhere in the message · `↑/↓` move · `Tab`/`Enter` accept · directories drill down · `Esc` closes only the current token menu'),
          ul(
            '**Two query modes**: path-like input (`@src/` `@./` `@~/` `@D:\\`) lists only that directory; plain fragments use **fuzzy subsequence match** (`@ink` hits `src/ink/Box.js`).',
            'Image paths auto-become `[Image #N]` attachments.',
          ),
          h3('Subagent panel (Ctrl+A)'),
          p('`↑/↓` browse · `Enter` view details · `Esc` close; details page `←/→` page, `X` interrupts while running; subagents render as live card rows. The panel mirrors every child this session dispatched — `subagent`/`send_message` runs, continuable re-dispatches (each new run resets the row), and workflow/ralph members — and re-folds durable discovery facts from the session log on resume, so restarting no longer blanks it. Historical rows without live timing show a `⚪` state instead of a fake duration.'),
          h3('Double-press Esc time-travel (rewind)'),
          p('List `↑/↓` + `Enter` to confirm · confirm page `Enter` rewind / `Esc` back · only `Esc` responds while a plugin decision is pending'),
        ],
      },
      {
        heading: 'Terminal compatibility',
        blocks: [
          p('iTerm2, kitty, WezTerm, Ghostty, and tmux provide the most complete extended-keyboard experience. Terminal.app consumes some Command shortcuts, so use Ctrl there. See [terminal requirements](../interface/#terminal) for more.'),
        ],
      },
    ],
  },
}

export default topic
